version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-local
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "123456"
      ACCEPT_EULA: "admin"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  mssql_data:
